# Generated by Django 3.2 on 2021-04-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='CartItems',
            new_name='OrderItem',
        ),
    ]
